# Voboost Configuration File

# Application Settings
settings-language: ru
settings-theme: light
settings-interface-shift-x: 0
settings-interface-shift-y: 0
settings-active-tab: store

# Vehicle Configuration
vehicle-fuel-mode: intellectual
vehicle-drive-mode: comfort

# Vehicle Model Settings
vehicle-model: free  # free or dreamer
